Payment
utopia-knights-tour/aaa-airlines-angular pull request #12
Opened 2020-04-29 06:02 UTC by allistergg

2020-04-30 02:21 UTC, AlexChavez235 approved these changes

2020-05-02 00:56 UTC, AlexChavez235 requested changes

2020-05-02 00:56 UTC, AlexChavez235 commented on src/app/_helpers/jwt.interceptor.ts
> +    console.log(currentUser);
remove logs

2020-05-02 00:56 UTC, AlexChavez235 commented on src/app/_services/auth.service.ts
> +                console.log(user);
remove logs

2020-05-02 00:56 UTC, AlexChavez235 commented on src/app/_services/store.service.ts
> +  store;
add type

2020-05-07 02:43 UTC, AlexChavez235 approved these changes

2020-05-07 22:13 UTC, alandchang-smoothstack approved these changes

2020-05-08 02:36 UTC, merged